project_id            = "circle-429006"
region                = "us-west2"
zone                  = "us-west2-b"
repository_id         = "circle-artifacts"
service_account_email = "circle-service@circle-429006.iam.gserviceaccount.com"
image_tag             = "20240710410"
mongo_uri             = "mongodb+srv://highhari:harilovesmongo@ciclecluster.1t5nbzl.mongodb.net/?retryWrites=true&w=majority&tls=true&appName=CicleCluster"
